import { z } from "zod";

const createCoachZodSchema = z.object({
  fullName: z.string().optional(),
  dob: z.string().optional(),
  age: z.number().optional(),
  gender: z.string().optional(),
  nationality: z.string().optional(),
  nationalityFlag: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional(),
  location: z.string().optional(),
  websiteUrl: z.string().url().optional(),
  license: z.string().optional(),
  experienceYears: z.number().optional(),
  specialization: z.string().optional(),
  keyAccomplishments: z.array(z.string()).optional(),
  totalMatches: z.number().optional(),
  wins: z.number().optional(),
  draws: z.number().optional(),
  losses: z.number().optional(),
  currentValue: z.number().optional(),
  salary: z.number().optional(),
  tactics: z.number().optional(),
  leadership: z.number().optional(),
  discipline: z.number().optional(),
});

const updateCoachZodSchema = z.object({
  userId: z.string().optional(),
  fullName: z.string().optional(),
  dob: z.string().optional(),
  age: z.number().optional(),
  gender: z.string().optional(),
  nationality: z.string().optional(),
  nationalityFlag: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional(),
  location: z.string().optional(),
  websiteUrl: z.string().url().optional(),
  license: z.string().optional(),
  experienceYears: z.number().optional(),
  specialization: z.string().optional(),
  keyAccomplishments: z.array(z.string()).optional(),
  totalMatches: z.number().optional(),
  wins: z.number().optional(),
  draws: z.number().optional(),
  losses: z.number().optional(),
  currentValue: z.number().optional(),
  salary: z.number().optional(),
  tactics: z.number().optional(),
  leadership: z.number().optional(),
  discipline: z.number().optional(),
});

export const CoachValidation = {
  createCoachZodSchema,
  updateCoachZodSchema,
};
